---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "Web address for GitHub repository"
author: "Name"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages
install.packages("tidyverse")
library(tidyverse)
install.packages("magrittr")
library(magrittr)
install.packages("dplyr")
library(dplyr)

# Set your ggplot theme

# Load your datasets
Health_Data_Raw <- read.csv("../ChanJacob_ENV872_EDA_FinalProject/Data/Raw/County Health Data 2021.csv", stringsAsFactors = TRUE)
```

```{r}
##Wrangling the dataset 

#Removing columns and rows conatining weblinks and other metadata 
Health_Data_Clean <- Health_Data_Raw[-c(1,2,3),-c(1,3, 4, 5, 6)] 

#Using a pipe to select and rename columns
Health_Data_Clean <- Health_Data_Clean %>%
  select(Bold.Indicator.Name.Text, NC, X.9, X.31, X.82, X.78) %>%
  rename(Indicators = Bold.Indicator.Name.Text, Bladen = X.9, Duplin = X.31, Sampson = X.82, Robeson = X.78)

#Transposing the data
Health_data_transposed <- t(Health_Data_Clean)

#Converting the transposed data to a dataframe
Health_data_transposed <- as.data.frame(Health_data_transposed)

#Adding a pipe statement to rename the columns
Health_data_transposed_clean <- Health_data_transposed %>%
  rename(Population = 1, Child_Population = 2, Elderly_Population = 3, White = 4, Hispanic_Latinx = 5, African_American = 6, American_Indian = 9, Reading_Proficiency = 12, Uninsured_Adults = 14, Medicaid_CHIP_enrolles = 16, Primary_Care_Physicians = 17, Low_Birthweight = 32, Infant_Mortality_Rate = 33, Poverty = 41, Air_Pollution = 52) 

#Selecting the required rows 
Health_data_transposed_clean_1 <- Health_data_transposed_clean[-c(1), -c(7,8, 10, 11, 13, 15, 18:31, 34:40, 42:51, 53:59)]

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
